/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jobamatching;

import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.HEIGHT;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class JobWeigh extends javax.swing.JFrame {

     Connection conector;
    Statement stmnt;
    ResultSet resultset;
    String sql;
    DefaultTableModel tbmodel;
    /**
     * Creates new form JobWeigh
     */
    public JobWeigh() {
        initComponents();
         jTable1.setSize(WIDTH, HEIGHT);
          connect();
          mergeTblModels();
        
    }

        public void connect(){
        try {
            Class.forName ("com.mysql.jdbc.Driver");
            conector=DriverManager.getConnection("jdbc:mysql://localhost:3306/JOBMATCH","root","admin");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JobWeigh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JobWeigh.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    public void mergeTblModels(){
        try {
            stmnt = conector.createStatement();
            sql = "select * from weight";
            resultset=stmnt.executeQuery(sql);            
            ResultSetMetaData tblmetadata= resultset.getMetaData();
            int numcols = tblmetadata.getColumnCount();
            String[] cols = new String[numcols];
            for(int i=1;i<=numcols;i++){
                cols[i-1]=tblmetadata.getColumnName(i);    
            }
            String[] row = new String[numcols+1];
            
            tbmodel = new DefaultTableModel(cols, 0);
            
            while(resultset.next()){
                for(int col=1;col<=numcols;col++){  
                    row[col-1] = resultset.getString(col);                                    
                }
                tbmodel.addRow(row);                 
            }
            tbmodel.addRow(new Object[numcols]);
            jTable1.setModel(tbmodel);
           jTable1.setValueAt(JobApp.JobRef.getText(), jTable1.getRowCount()-1, 0);
            jTable1.setValueAt(JobApp.JobTitle.getSelectedItem(), jTable1.getRowCount()-1, 1);
          
        } catch (SQLException ex) {
            Logger.getLogger(JobWeigh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Weigh Job Specs");
        setBackground(new java.awt.Color(0, 0, 204));
        setMaximumSize(new java.awt.Dimension(5000, 500));
        setMinimumSize(new java.awt.Dimension(200, 200));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setText("Weigh your job specifications");

        jButton1.setText("Assign Weight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(564, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTable1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
           
        String d="";
        for(int i=0;i<editor.length();i++){
            if(editor.charAt(i)>='0'&& editor.charAt(i)<='9')
                d+=editor.charAt(i);
        }
        if(editor.isEmpty())
            d=jTable1.getValueAt(jTable1.getRowCount()-1, jTable1.getColumnCount()-1).toString();
        System.out.println(d);
             int adder=jTable1.getRowCount()-1;    
             
             int c3=Integer.parseInt((String)jTable1.getValueAt(adder, 2)),
                 c4=Integer.parseInt((String)jTable1.getValueAt(adder, 3)),
                 c5=Integer.parseInt((String)jTable1.getValueAt(adder, 4)),
                 c6=Integer.parseInt((String)jTable1.getValueAt(adder, 5)),
                 c7=Integer.parseInt((String)jTable1.getValueAt(adder, 6)),
                 c8=Integer.parseInt((String)jTable1.getValueAt(adder, 7)),
                 c9=Integer.parseInt((String)jTable1.getValueAt(adder, 8)),
                 c10=Integer.parseInt((String)jTable1.getValueAt(adder, 9)),
                 c11=Integer.parseInt((String)jTable1.getValueAt(adder, 10)),
                 c12=Integer.parseInt((String)jTable1.getValueAt(adder, 11)),
                 c13=Integer.parseInt((String)jTable1.getValueAt(adder, 12)),
                 c14=Integer.parseInt((String)jTable1.getValueAt(adder, 13)),
                 c15=Integer.parseInt(d),
                 c16=Integer.parseInt(d),                 
                 c17=Integer.parseInt(d);
             
             sql="insert into weight values('"+jTable1.getValueAt(adder, 0)+"','"+jTable1.getValueAt(adder, 1)+"',"
                     + "'"+c3+"','"+c4+"','"+c5+"',"
                     + "'"+c6+"','"+c7+"','"+c8+"',"
                     + "'"+c9+"','"+c10+"','"+c11+"',"
                     + "'"+c12+"','"+c13+"','"+c14+"',"
                     + "'"+c15+"');";
             
             DBClass db = new DBClass();
             db.update(sql);
             
             JOptionPane.showMessageDialog(rootPane, "weight assigned successfully");
             this.dispose();
             // TODO add your handling code here:
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, ex.getMessage());
         }
        catch(Exception e){
             JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost

        //JOptionPane.showMessageDialog(rootPane, "Focus Lost");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusLost

    private void jTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseExited
          
        
    }//GEN-LAST:event_jTable1MouseExited

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
       // jTable1.setValueAt(evt.getKeyChar(), jTable1.getEditingRow(), jTable1.getEditingColumn());
           if(evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)
               editor="";
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
         if(jTable1.getSelectedRow()==(jTable1.getRowCount()-1) && jTable1.getSelectedColumn()==jTable1.getColumnCount()-1){
            editor +=evt.getKeyChar();       
       } 
         System.out.println(editor);
         // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobWeigh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobWeigh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobWeigh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobWeigh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobWeigh().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
String editor="";
}
